# Generated by Django 4.2 on 2023-05-02 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20230427_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(default='admin', max_length=150, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surnames',
            field=models.CharField(max_length=150, verbose_name='Apellido(s)'),
        ),
    ]
