# Generated by Django 3.0.4 on 2023-05-11 17:00

import core.erp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20230503_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='', max_length=150, verbose_name=core.erp.models.Product)),
                ('prod_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod_cant', models.IntegerField(default=0)),
                ('prod_fecha', models.DateField(default=datetime.datetime.now)),
                ('prod_tipo', models.CharField(default='V', max_length=1)),
                ('prod_estado', models.CharField(default='R', max_length=1)),
            ],
        ),
    ]
