# Generated by Django 3.0.4 on 2023-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_cardex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardex',
            name='prod_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
