# Generated by Django 3.0.4 on 2023-05-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20230515_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardex',
            name='prod_sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.Sale'),
        ),
    ]
