# Generated by Django 3.0.4 on 2023-05-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_cardex_prod_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardex',
            name='prod_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale'),
        ),
    ]
