# Generated by Django 3.0.4 on 2023-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20230515_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardex',
            name='prod_sale',
            field=models.IntegerField(default=0),
        ),
    ]
