# Generated by Django 3.0.4 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20230515_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardex',
            name='prod_id',
            field=models.IntegerField(default=0),
        ),
    ]
