# Generated by Django 3.0.4 on 2023-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_cardex_prod_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardex',
            name='prod_user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
